// Code generated by ogen, DO NOT EDIT.
package oas

type CreateTodoRes interface {
	createTodoRes()
}

type DeleteTodoRes interface {
	deleteTodoRes()
}

type GetTodoRes interface {
	getTodoRes()
}

type UpdateTodoRes interface {
	updateTodoRes()
}
