// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// TodoGet implements GET /todo operation.
//
// Search.
//
// GET /todo
func (UnimplementedHandler) TodoGet(ctx context.Context) (r TodoGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
