// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/pkg/ent/schema"
	"server/pkg/ent/task"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescAge is the schema descriptor for age field.
	taskDescAge := taskFields[0].Descriptor()
	// task.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	task.AgeValidator = taskDescAge.Validators[0].(func(int) error)
	// taskDescName is the schema descriptor for name field.
	taskDescName := taskFields[1].Descriptor()
	// task.DefaultName holds the default value on creation for the name field.
	task.DefaultName = taskDescName.Default.(string)
}
