-- Create "todos" table
CREATE TABLE "todos" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "description" character varying NOT NULL, "start_at" timestamptz NOT NULL, "end_at" timestamptz NOT NULL, "priority" character varying NOT NULL, "status" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "labels" table
CREATE TABLE "labels" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "todo_labels" table
CREATE TABLE "todo_labels" ("todo_id" bigint NOT NULL, "label_id" bigint NOT NULL, PRIMARY KEY ("todo_id", "label_id"), CONSTRAINT "todo_labels_todo_id" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON DELETE CASCADE, CONSTRAINT "todo_labels_label_id" FOREIGN KEY ("label_id") REFERENCES "labels" ("id") ON DELETE CASCADE);
