openapi: 3.1.0
info:
  title: todo-schema-driven
  description: ""
  version: 1.0.0
tags:
  - name: Todo
paths:
  /todo:
    get:
      summary: Search
      deprecated: false
      description: ""
      tags:
        - Todo
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoBase"
          headers: {}
        "400":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
        "500":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          headers: {}
      security: []
components:
  schemas:
    TodoBase:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        start_at:
          type: string
          format: date-time
        end_at:
          type: string
          format: date-time
          x-nullable: true
        priority:
          $ref: "#/components/schemas/Priority"
        status:
          $ref: "#/components/schemas/TodoStatus"
      required:
        - id
        - title
        - description
        - start_at
        - priority
        - status
    Priority:
      type: object
      properties:
        name:
          type: string
        label:
          type: string
        color:
          type: string
        bgColor:
          type: string
      required:
        - name
        - label
        - color
        - bgColor
    TodoStatus:
      type: object
      properties:
        name:
          type: string
        label:
          type: string
        color:
          type: string
        bgColor:
          type: string
      required:
        - name
        - label
        - color
        - bgColor
    ErrorResponse:
      type: object
      properties:
        globalErrors:
          type: array
          items:
            type: string
        fieldErrors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              messages:
                type: array
                items:
                  type: string
            required:
              - field
              - messages
      required:
        - globalErrors
        - fieldErrors
  securitySchemes: {}
servers: []

