FROM golang:1.23-bullseye
ENV TZ=Asia/Tokyo
WORKDIR /src/server


# server 立てたら
# RUN go install -v github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]

