// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Label is the predicate function for label builders.
type Label func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)
